/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as MediaIdRouteRouteImport } from './routes/media.$id/route'
import { Route as MediaIdIndexRouteImport } from './routes/media.$id/index'
import { Route as MediaIdPlayRouteImport } from './routes/media.$id/play'

const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRouteRoute,
} as any)
const MediaIdRouteRoute = MediaIdRouteRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIdIndexRoute = MediaIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaIdRouteRoute,
} as any)
const MediaIdPlayRoute = MediaIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => MediaIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRouteRouteWithChildren
  '/media/$id': typeof MediaIdRouteRouteWithChildren
  '/search/': typeof SearchIndexRoute
  '/media/$id/play': typeof MediaIdPlayRoute
  '/media/$id/': typeof MediaIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchIndexRoute
  '/media/$id/play': typeof MediaIdPlayRoute
  '/media/$id': typeof MediaIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRouteRouteWithChildren
  '/media/$id': typeof MediaIdRouteRouteWithChildren
  '/search/': typeof SearchIndexRoute
  '/media/$id/play': typeof MediaIdPlayRoute
  '/media/$id/': typeof MediaIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/media/$id'
    | '/search/'
    | '/media/$id/play'
    | '/media/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/media/$id/play' | '/media/$id'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/media/$id'
    | '/search/'
    | '/media/$id/play'
    | '/media/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRouteRoute: typeof SearchRouteRouteWithChildren
  MediaIdRouteRoute: typeof MediaIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRouteRoute
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$id/': {
      id: '/media/$id/'
      path: '/'
      fullPath: '/media/$id/'
      preLoaderRoute: typeof MediaIdIndexRouteImport
      parentRoute: typeof MediaIdRouteRoute
    }
    '/media/$id/play': {
      id: '/media/$id/play'
      path: '/play'
      fullPath: '/media/$id/play'
      preLoaderRoute: typeof MediaIdPlayRouteImport
      parentRoute: typeof MediaIdRouteRoute
    }
  }
}

interface SearchRouteRouteChildren {
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteRouteChildren: SearchRouteRouteChildren = {
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteRouteWithChildren = SearchRouteRoute._addFileChildren(
  SearchRouteRouteChildren,
)

interface MediaIdRouteRouteChildren {
  MediaIdPlayRoute: typeof MediaIdPlayRoute
  MediaIdIndexRoute: typeof MediaIdIndexRoute
}

const MediaIdRouteRouteChildren: MediaIdRouteRouteChildren = {
  MediaIdPlayRoute: MediaIdPlayRoute,
  MediaIdIndexRoute: MediaIdIndexRoute,
}

const MediaIdRouteRouteWithChildren = MediaIdRouteRoute._addFileChildren(
  MediaIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRouteRoute: SearchRouteRouteWithChildren,
  MediaIdRouteRoute: MediaIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
