/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteRouteImport } from './routes/search/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as SearchIdRouteRouteImport } from './routes/search/$id/route'
import { Route as MediaIdRouteRouteImport } from './routes/media.$id/route'

const SearchRouteRoute = SearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRouteRoute,
} as any)
const SearchIdRouteRoute = SearchIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SearchRouteRoute,
} as any)
const MediaIdRouteRoute = MediaIdRouteRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRouteRouteWithChildren
  '/media/$id': typeof MediaIdRouteRoute
  '/search/$id': typeof SearchIdRouteRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media/$id': typeof MediaIdRouteRoute
  '/search/$id': typeof SearchIdRouteRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRouteRouteWithChildren
  '/media/$id': typeof MediaIdRouteRoute
  '/search/$id': typeof SearchIdRouteRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/media/$id' | '/search/$id' | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/media/$id' | '/search/$id' | '/search'
  id: '__root__' | '/' | '/search' | '/media/$id' | '/search/$id' | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRouteRoute: typeof SearchRouteRouteWithChildren
  MediaIdRouteRoute: typeof MediaIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRouteRoute
    }
    '/search/$id': {
      id: '/search/$id'
      path: '/$id'
      fullPath: '/search/$id'
      preLoaderRoute: typeof SearchIdRouteRouteImport
      parentRoute: typeof SearchRouteRoute
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SearchRouteRouteChildren {
  SearchIdRouteRoute: typeof SearchIdRouteRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteRouteChildren: SearchRouteRouteChildren = {
  SearchIdRouteRoute: SearchIdRouteRoute,
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteRouteWithChildren = SearchRouteRoute._addFileChildren(
  SearchRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRouteRoute: SearchRouteRouteWithChildren,
  MediaIdRouteRoute: MediaIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
